-- ════════════════════════════════════════════════════════════════
--  إدارة الفئات — جدول categories + ربط المنتجات بعدة فئات
--
--  - جدول categories (id, name, sort_order) لترتيب الفئات.
--  - عمود category_ids (مصفوفة) على products: كل منتج يقدر ينتمي
--    لفئة واحدة أو أكثر.
--  - RLS: القراءة للجميع، الكتابة للمسجّلين (متوافق مع باقي الجداول).
--  - تعبئة أولية: "حصري بن وقناد" أولاً، ثم الفئات الحالية، وربط كل
--    منتج بفئته الحالية.
--
--  شغّله مرة واحدة في: Supabase Dashboard ▸ SQL Editor ▸ Run.
-- ════════════════════════════════════════════════════════════════

-- ─────────── جدول الفئات ───────────
create table if not exists categories (
  id         bigint generated by default as identity primary key,
  name       text   not null,
  sort_order int    not null default 0,
  created_at timestamptz default now()
);

-- RLS
alter table categories enable row level security;

drop policy if exists "categories_select_all"  on categories;
drop policy if exists "categories_insert_auth" on categories;
drop policy if exists "categories_update_auth" on categories;
drop policy if exists "categories_delete_auth" on categories;

create policy "categories_select_all"  on categories for select to anon, authenticated using (true);
create policy "categories_insert_auth" on categories for insert to authenticated with check (true);
create policy "categories_update_auth" on categories for update to authenticated using (true) with check (true);
create policy "categories_delete_auth" on categories for delete to authenticated using (true);

-- ─────────── انتماء المنتج لعدة فئات ───────────
alter table products add column if not exists category_ids bigint[] default '{}';

-- ─────────── تعبئة أولية ───────────
-- 1) "حصري بن وقناد" كأول فئة (sort_order = 0)
insert into categories (name, sort_order)
select 'حصري بن وقناد', 0
where not exists (select 1 from categories where name = 'حصري بن وقناد');

-- 2) الفئات الحالية المميّزة من المنتجات (بعد الحصري)
insert into categories (name, sort_order)
select distinct on ("Category") "Category",
       (select coalesce(max(sort_order), 0) from categories)
         + row_number() over (order by "Category")
from products
where "Category" is not null and trim("Category") <> ''
  and "Category" not in (select name from categories);

-- 3) ربط كل منتج بفئته الحالية (للمنتجات التي لم تُربط بعد)
update products p
set category_ids = array[c.id]
from categories c
where p."Category" = c.name
  and (p.category_ids is null or p.category_ids = '{}');
