-- ════════════════════════════════════════════════════════════════
--  رسوم التوصيل بالمنطقة
--
--  - جدول delivery_zones (id, name, fee, sort_order): قائمة مناطق
--    ثابتة، كل منطقة لها رسم توصيل. RLS: قراءة للجميع، كتابة للمسجّلين.
--  - عمود delivery_fee على orders لحفظ رسم التوصيل مع الطلب.
--  - تعبئة أولية بمحافظات الكويت (عدّل الرسوم من اللوحة حسب الحاجة).
--
--  شغّله مرة واحدة في: Supabase Dashboard ▸ SQL Editor ▸ Run.
-- ════════════════════════════════════════════════════════════════

create table if not exists delivery_zones (
  id         bigint generated by default as identity primary key,
  name       text    not null,
  fee        numeric not null default 0,
  sort_order int     not null default 0,
  created_at timestamptz default now()
);

alter table delivery_zones enable row level security;

drop policy if exists "zones_select_all"  on delivery_zones;
drop policy if exists "zones_insert_auth" on delivery_zones;
drop policy if exists "zones_update_auth" on delivery_zones;
drop policy if exists "zones_delete_auth" on delivery_zones;

create policy "zones_select_all"  on delivery_zones for select to anon, authenticated using (true);
create policy "zones_insert_auth" on delivery_zones for insert to authenticated with check (true);
create policy "zones_update_auth" on delivery_zones for update to authenticated using (true) with check (true);
create policy "zones_delete_auth" on delivery_zones for delete to authenticated using (true);

-- رسم التوصيل على الطلبات
alter table orders add column if not exists delivery_fee numeric default 0;

-- تعبئة أولية (عدّل الأسماء والرسوم من قسم "رسوم التوصيل" في اللوحة)
insert into delivery_zones (name, fee, sort_order)
select v.name, v.fee, v.sort_order
from (values
  ('محافظة العاصمة',     1.500, 1),
  ('حولي',               1.500, 2),
  ('الفروانية',          1.500, 3),
  ('الأحمدي',            2.000, 4),
  ('الجهراء',            2.500, 5),
  ('مبارك الكبير',       1.500, 6)
) as v(name, fee, sort_order)
where not exists (select 1 from delivery_zones);
