-- ════════════════════════════════════════════════════════════════
--  أكواد الخصم
--
--  - جدول discount_codes: الكود، نوع الخصم (percent/fixed)، القيمة،
--    تاريخ الانتهاء، الحد الأقصى للاستخدامات، عداد الاستخدامات، الحالة.
--  - الأمان: الزائر (anon) لا يقرأ الجدول مباشرة (حتى لا تتسرّب الأكواد).
--    يتحقق ويستخدم عبر دالتي RPC فقط. الأدمن (authenticated) يدير الجدول.
--  - عمودان على orders: discount_code, discount_amount.
--
--  شغّله مرة واحدة في: Supabase Dashboard ▸ SQL Editor ▸ Run.
-- ════════════════════════════════════════════════════════════════

create table if not exists discount_codes (
  id            bigint generated by default as identity primary key,
  code          text    not null unique,
  discount_type text    not null default 'percent',   -- 'percent' | 'fixed'
  discount_value numeric not null default 0,
  expires_at    timestamptz,                           -- null = بلا انتهاء
  max_uses      int,                                   -- null = بلا حدّ
  used_count    int     not null default 0,
  active        boolean not null default true,
  created_at    timestamptz default now()
);

-- RLS: الأدمن (authenticated) فقط يدير الجدول مباشرة. anon لا يقرأ مباشرة.
alter table discount_codes enable row level security;

drop policy if exists "discounts_select_auth" on discount_codes;
drop policy if exists "discounts_insert_auth" on discount_codes;
drop policy if exists "discounts_update_auth" on discount_codes;
drop policy if exists "discounts_delete_auth" on discount_codes;

create policy "discounts_select_auth" on discount_codes for select to authenticated using (true);
create policy "discounts_insert_auth" on discount_codes for insert to authenticated with check (true);
create policy "discounts_update_auth" on discount_codes for update to authenticated using (true) with check (true);
create policy "discounts_delete_auth" on discount_codes for delete to authenticated using (true);

-- ── دالة التحقق: ترجع الخصم لكود صالح فقط (بدون كشف باقي الأكواد) ──
create or replace function validate_discount(p_code text)
returns table (code text, discount_type text, discount_value numeric)
language sql security definer set search_path = public as $$
  select d.code, d.discount_type, d.discount_value
  from discount_codes d
  where lower(d.code) = lower(trim(p_code))
    and d.active = true
    and (d.expires_at is null or d.expires_at > now())
    and (d.max_uses  is null or d.used_count < d.max_uses)
  limit 1;
$$;

-- ── دالة الاستخدام: تزيد العداد ذرّياً إن كان الكود لا يزال صالحاً ──
create or replace function redeem_discount(p_code text)
returns boolean
language plpgsql security definer set search_path = public as $$
declare affected int;
begin
  update discount_codes
  set used_count = used_count + 1
  where lower(code) = lower(trim(p_code))
    and active = true
    and (expires_at is null or expires_at > now())
    and (max_uses  is null or used_count < max_uses);
  get diagnostics affected = row_count;
  return affected > 0;
end;
$$;

-- السماح للزائر والمسجّل باستدعاء الدالتين فقط
grant execute on function validate_discount(text) to anon, authenticated;
grant execute on function redeem_discount(text)  to anon, authenticated;

-- ── حفظ الخصم على الطلب ──
alter table orders add column if not exists discount_code   text;
alter table orders add column if not exists discount_amount numeric default 0;
