-- ════════════════════════════════════════════════════════════════
--  نظام الولاء (نقاط)
--
--  - جدول loyalty_points (رقم الهاتف، النقاط، آخر تحديث).
--  - جدول app_settings (مفتاح/قيمة) — يحوي loyalty_enabled لتفعيل/تعطيل النظام.
--  - الكسب: 1 د.ك إنفاق (منتجات بعد الخصم، بلا توصيل) = 1 نقطة، عند اكتمال الطلب.
--  - الاستخدام: 100 نقطة = 1 د.ك خصم (لا يشمل التوصيل).
--  - الأمان: الزائر لا يقرأ جدول النقاط مباشرة. يستعلم/يستخدم عبر RPC.
--    الأدمن (authenticated) يدير الجدول ويمنح النقاط.
--  - أعمدة على orders: points_awarded, loyalty_points_used, loyalty_discount.
--
--  شغّله مرة واحدة في: Supabase Dashboard ▸ SQL Editor ▸ Run.
-- ════════════════════════════════════════════════════════════════

-- ─────────── جدول النقاط ───────────
create table if not exists loyalty_points (
  id             bigint generated by default as identity primary key,
  customer_phone text not null unique,
  points         int  not null default 0,
  updated_at     timestamptz default now()
);

alter table loyalty_points enable row level security;
drop policy if exists "loyalty_select_auth" on loyalty_points;
drop policy if exists "loyalty_insert_auth" on loyalty_points;
drop policy if exists "loyalty_update_auth" on loyalty_points;
drop policy if exists "loyalty_delete_auth" on loyalty_points;
create policy "loyalty_select_auth" on loyalty_points for select to authenticated using (true);
create policy "loyalty_insert_auth" on loyalty_points for insert to authenticated with check (true);
create policy "loyalty_update_auth" on loyalty_points for update to authenticated using (true) with check (true);
create policy "loyalty_delete_auth" on loyalty_points for delete to authenticated using (true);

-- ─────────── إعدادات عامة (تفعيل النظام) ───────────
create table if not exists app_settings (
  key   text primary key,
  value text
);
alter table app_settings enable row level security;
drop policy if exists "settings_select_all" on app_settings;
drop policy if exists "settings_write_auth"  on app_settings;
create policy "settings_select_all" on app_settings for select to anon, authenticated using (true);
create policy "settings_write_auth"  on app_settings for all    to authenticated using (true) with check (true);

insert into app_settings (key, value) values
  ('loyalty_enabled',     'true'),     -- تفعيل النظام كامل (الكسب)
  ('loyalty_show',        'true'),     -- إظهار النقاط للزبون في المتجر
  ('loyalty_redeem',      'true'),     -- السماح باستخدام النقاط كخصم
  ('loyalty_reward_type', 'points'),   -- 'points' | 'cashback'
  ('loyalty_earn_rate',   '1')         -- نقاط لكل 1 د.ك (أو % كاشباك)
on conflict (key) do nothing;

-- ─────────── أعمدة على الطلبات ───────────
alter table orders add column if not exists points_awarded      boolean default false;
alter table orders add column if not exists loyalty_points_used int     default 0;
alter table orders add column if not exists loyalty_discount     numeric default 0;

-- ─────────── دوال RPC ───────────
-- استعلام نقاط زبون (للزائر) — يرجّع 0 لو ما له رصيد
create or replace function get_loyalty_points(p_phone text)
returns int language sql security definer set search_path = public as $$
  select coalesce((select points from loyalty_points where customer_phone = trim(p_phone)), 0);
$$;

-- استخدام نقاط (للزائر) — يخصم إن كان النظام مفعّلاً والرصيد كافياً
create or replace function redeem_loyalty(p_phone text, p_points int)
returns boolean language plpgsql security definer set search_path = public as $$
declare enabled boolean; redeemable boolean; affected int;
begin
  select coalesce((select value from app_settings where key = 'loyalty_enabled'), 'true') = 'true' into enabled;
  select coalesce((select value from app_settings where key = 'loyalty_redeem'),  'true') = 'true' into redeemable;
  if not enabled or not redeemable or p_points <= 0 then return false; end if;
  update loyalty_points set points = points - p_points, updated_at = now()
   where customer_phone = trim(p_phone) and points >= p_points;
  get diagnostics affected = row_count;
  return affected > 0;
end; $$;

-- منح نقاط (للأدمن) — إنشاء أو زيادة رصيد الزبون
create or replace function award_loyalty(p_phone text, p_points int)
returns void language plpgsql security definer set search_path = public as $$
begin
  if p_points <= 0 or coalesce(trim(p_phone), '') = '' then return; end if;
  insert into loyalty_points (customer_phone, points, updated_at)
    values (trim(p_phone), p_points, now())
  on conflict (customer_phone)
    do update set points = loyalty_points.points + excluded.points, updated_at = now();
end; $$;

-- مهم: Postgres يمنح EXECUTE لـ PUBLIC تلقائياً للدوال الجديدة.
-- نلغيه أولاً ثم نمنح الأدوار المطلوبة صراحةً — وإلا يقدر الزائر يستدعي award_loyalty ويمنح نفسه نقاطاً.
revoke execute on function get_loyalty_points(text)  from public;
revoke execute on function redeem_loyalty(text, int) from public;
revoke execute on function award_loyalty(text, int)  from public;

grant execute on function get_loyalty_points(text)     to anon, authenticated;
grant execute on function redeem_loyalty(text, int)     to anon, authenticated;
grant execute on function award_loyalty(text, int)      to authenticated;   -- الأدمن فقط
