-- ════════════════════════════════════════════════════════════════
--  إشعارات تيليغرام للطلبات الجديدة
--
--  - جدول telegram_chats (chat_id, label, enabled): قائمة معرّفات
--    محادثات تيليغرام التي يصلها إشعار عند كل طلب جديد.
--  - RLS: لا وصول لـ anon إطلاقاً (لا تُكشف المعرّفات للزوّار)؛
--    القراءة/الكتابة للمسجّلين فقط (لوحة التحكم).
--  - الإرسال الفعلي يتم في api/notify-telegram.js عبر Database Webhook
--    على جدول orders (يقرأ هذا الجدول بمفتاح service_role، يتجاوز RLS).
--
--  شغّله مرة واحدة في: Supabase Dashboard ▸ SQL Editor ▸ Run.
-- ════════════════════════════════════════════════════════════════

create table if not exists telegram_chats (
  id         bigint generated by default as identity primary key,
  chat_id    text    not null unique,
  label      text,
  enabled    boolean not null default true,
  created_at timestamptz default now()
);

alter table telegram_chats enable row level security;

-- ملاحظة: لا توجد سياسة لـ anon — الزوّار لا يقرأون ولا يكتبون المعرّفات.
drop policy if exists "tg_select_auth" on telegram_chats;
drop policy if exists "tg_insert_auth" on telegram_chats;
drop policy if exists "tg_update_auth" on telegram_chats;
drop policy if exists "tg_delete_auth" on telegram_chats;

create policy "tg_select_auth" on telegram_chats for select to authenticated using (true);
create policy "tg_insert_auth" on telegram_chats for insert to authenticated with check (true);
create policy "tg_update_auth" on telegram_chats for update to authenticated using (true) with check (true);
create policy "tg_delete_auth" on telegram_chats for delete to authenticated using (true);

-- ────────────────────────────────────────────────────────────────
--  إعداد الـ Webhook (يدوياً، مرة واحدة):
--  Supabase Dashboard ▸ Database ▸ Webhooks ▸ Create a new hook
--    Name:    notify_telegram_on_new_order
--    Table:   public.orders
--    Events:  Insert + Update
--    Type:    HTTP Request ▸ POST
--    URL:     https://www.bnwgnad.com/api/notify-telegram  (النطاق النهائي بدون redirect)
--    Headers: x-webhook-secret = <نفس قيمة TELEGRAM_WEBHOOK_SECRET في Vercel>
--  الدالة نفسها تتجاهل أي تحديث لا يحوّل حالة الطلب إلى 'new'،
--  فلا تتكرر الإشعارات (طلب البطاقة: pending_payment → new).
-- ────────────────────────────────────────────────────────────────
